language: java

dist: xenial

sudo: false

jdk:
  - oraclejdk11
  - openjdk11
  - oraclejdk9
  - openjdk9
  - openjdk8

matrix:
  include:
    - jdk: openjdk9
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"

env:
  matrix:
    - APIVERSION='31'
    - APIVERSION='40'

install: mvn install -DskipTests=true -Dgpg.skip=true

script: mvn verify -Dgpg.skip=true -Dmaven.javadoc.skip=true
