language: java

dist: xenial

sudo: false

jdk:
  - openjdk11
  - openjdk9
  - openjdk8

env:
  matrix:
    - APIVERSION='31'
    - APIVERSION='40'

install: mvn install -DskipTests=true -Dgpg.skip=true

script: mvn verify -Dgpg.skip=true -Dmaven.javadoc.skip=true
